Fixed a key lookup failure.
If you run `sphinx-build -b swagger srs dest`, you get this error:
```
Exception occurred:
  File "c:\users\moigagoo\projects\venvs\sloth-ci\lib\site-packages\sphinxswagger\writer.py", line 126, in depart_desc
    responses[default].setdefault('headers', {})
KeyError: 'default'
```
This happens because `responses` is an empty dict, it has no `"default"` key.

This tiny patch fixes it.